spring:
  application:
    name: itau-code-challenge-core-banking

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:consulta-saldo-consumer}
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual

dynamodb:
  endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}
  region: ${DYNAMODB_REGION:us-east-1}