### Consulta de saldo existente
GET http://localhost:8080/balances/5b19c8b6-0cc4-4c72-a989-0c2ee15fa975
Accept: application/json

### Conta inexistente (404)
GET http://localhost:8080/balances/00000000-0000-0000-0000-000000000000
Accept: application/json

### UUID inválido (400)
GET http://localhost:8080/balances/isso-nao-e-um-uuid
Accept: application/json